spring:
  r2dbc:
    url: "r2dbc:pool:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}"
    username: "${MYSQLUSER}"
    password: "${MYSQLPASSWORD}"
  application:
    name: base

server:
  port: "${PORT:8080}"